String varname1 = ""
+ "-- MySQL Script generated by MySQL Workbench "
+ "-- Thu Feb  9 16:55:05 2023 "
+ "-- Model: New Model    Version: 1.0 "
+ "-- MySQL Workbench Forward Engineering "
+ " "
+ "SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;";


String varname11 = ""
+ "SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;";


String varname12 = ""
+ "SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'; "
+ " "
+ "-- ----------------------------------------------------- "
+ "-- Schema ristorante_teamproject "
+ "-- ----------------------------------------------------- "
+ " "
+ "-- ----------------------------------------------------- "
+ "-- Schema ristorante_teamproject "
+ "-- -----------------------------------------------------";


String varname13 = ""
+ "CREATE SCHEMA IF NOT EXISTS `ristorante_teamproject` DEFAULT CHARACTER SET utf8 ;";


String varname14 = ""
+ "USE `ristorante_teamproject` ; "
+ " "
+ "-- ----------------------------------------------------- "
+ "-- Table `ristorante_teamproject`.`client` "
+ "-- -----------------------------------------------------";


String varname15 = ""
+ "CREATE TABLE IF NOT EXISTS `ristorante_teamproject`.`client` ( "
+ "  `idcliente` INT NOT NULL AUTO_INCREMENT, "
+ "  `name` VARCHAR(30) NOT NULL, "
+ "  `surname` VARCHAR(30) NOT NULL, "
+ "  `age` INT NOT NULL, "
+ "  `city` VARCHAR(30) NOT NULL, "
+ "  `gender` ENUM(\"M\", \"F\", \"A\") NOT NULL, "
+ "  `cell_number` VARCHAR(14) NOT NULL, "
+ "  `email` VARCHAR(30) NOT NULL, "
+ "  PRIMARY KEY (`idcliente`), "
+ "  UNIQUE INDEX `numero_telefono_UNIQUE` (`cell_number` ASC) VISIBLE, "
+ "  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE) "
+ "ENGINE = InnoDB; "
+ " "
+ " "
+ "-- ----------------------------------------------------- "
+ "-- Table `ristorante_teamproject`.`restaurant` "
+ "-- -----------------------------------------------------";


String varname16 = ""
+ "CREATE TABLE IF NOT EXISTS `ristorante_teamproject`.`restaurant` ( "
+ "  `idRistorante` INT NOT NULL AUTO_INCREMENT, "
+ "  `name` VARCHAR(45) NOT NULL, "
+ "  `max_table` INT NOT NULL, "
+ "  `via` VARCHAR(45) NOT NULL, "
+ "  `citta` VARCHAR(45) NOT NULL, "
+ "  `num_telefono` VARCHAR(20) NOT NULL, "
+ "  `prezzo_medio` DOUBLE NOT NULL, "
+ "  `tipologia` VARCHAR(45) NOT NULL, "
+ "  `valutazione_ristorante` VARCHAR(45) NOT NULL, "
+ "  `metodo_pagamento` VARCHAR(45) NOT NULL, "
+ "  PRIMARY KEY (`idRistorante`), "
+ "  UNIQUE INDEX `num_telefono_UNIQUE` (`num_telefono` ASC) VISIBLE) "
+ "ENGINE = InnoDB; "
+ " "
+ " "
+ "-- ----------------------------------------------------- "
+ "-- Table `ristorante_teamproject`.`menu` "
+ "-- -----------------------------------------------------";


String varname17 = ""
+ "CREATE TABLE IF NOT EXISTS `ristorante_teamproject`.`menu` ( "
+ "  `idmenu` INT NOT NULL AUTO_INCREMENT, "
+ "  `name` VARCHAR(30) NOT NULL, "
+ "  `preference_enum` ENUM(\"VEGETARIANO\", \"VEGANO\", \"ONNIVORO\") NULL, "
+ "  `menucol` VARCHAR(45) NULL, "
+ "  `restaurant_idRistorante` INT NOT NULL, "
+ "  PRIMARY KEY (`idmenu`), "
+ "  INDEX `fk_menu_restaurant1_idx` (`restaurant_idRistorante` ASC) VISIBLE, "
+ "  CONSTRAINT `fk_menu_restaurant1` "
+ "    FOREIGN KEY (`restaurant_idRistorante`) "
+ "    REFERENCES `ristorante_teamproject`.`restaurant` (`idRistorante`) "
+ "    ON DELETE NO ACTION "
+ "    ON UPDATE NO ACTION) "
+ "ENGINE = InnoDB; "
+ " "
+ " "
+ "-- ----------------------------------------------------- "
+ "-- Table `ristorante_teamproject`.`dish` "
+ "-- -----------------------------------------------------";


String varname18 = ""
+ "CREATE TABLE IF NOT EXISTS `ristorante_teamproject`.`dish` ( "
+ "  `idPortata` INT NOT NULL AUTO_INCREMENT, "
+ "  `name` VARCHAR(45) NOT NULL, "
+ "  `price` DOUBLE NOT NULL, "
+ "  `type` ENUM(\"PRIMO\", \"SECONDO\", \"DESSERT\", \"BEVANDE\") NOT NULL, "
+ "  `Portatacol` VARCHAR(45) NULL, "
+ "  `menu_idmenu` INT NOT NULL, "
+ "  PRIMARY KEY (`idPortata`), "
+ "  INDEX `fk_dish_menu_idx` (`menu_idmenu` ASC) VISIBLE, "
+ "  CONSTRAINT `fk_dish_menu` "
+ "    FOREIGN KEY (`menu_idmenu`) "
+ "    REFERENCES `ristorante_teamproject`.`menu` (`idmenu`) "
+ "    ON DELETE NO ACTION "
+ "    ON UPDATE NO ACTION) "
+ "ENGINE = InnoDB; "
+ " "
+ " "
+ "-- ----------------------------------------------------- "
+ "-- Table `ristorante_teamproject`.`table` "
+ "-- -----------------------------------------------------";


String varname19 = ""
+ "CREATE TABLE IF NOT EXISTS `ristorante_teamproject`.`table` ( "
+ "  `idtable` INT NOT NULL AUTO_INCREMENT, "
+ "  `state_enum` ENUM(\"RESERVED\", \"OCCUPIED\", \"FREE\") NULL, "
+ "  `tablecol` VARCHAR(45) NULL, "
+ "  PRIMARY KEY (`idtable`)) "
+ "ENGINE = InnoDB; "
+ " "
+ " "
+ "-- ----------------------------------------------------- "
+ "-- Table `ristorante_teamproject`.`booking` "
+ "-- -----------------------------------------------------";


String varname110 = ""
+ "CREATE TABLE IF NOT EXISTS `ristorante_teamproject`.`booking` ( "
+ "  `idbooking` INT NOT NULL AUTO_INCREMENT, "
+ "  `date_time` VARCHAR(45) NOT NULL, "
+ "  `people_number` INT NOT NULL, "
+ "  `is_holiday` TINYINT NOT NULL, "
+ "  `table_idtable` INT NOT NULL, "
+ "  `client_idcliente` INT NOT NULL, "
+ "  `restaurant_idRistorante` INT NOT NULL, "
+ "  PRIMARY KEY (`idbooking`), "
+ "  INDEX `fk_booking_table1_idx` (`table_idtable` ASC) VISIBLE, "
+ "  INDEX `fk_booking_client1_idx` (`client_idcliente` ASC) VISIBLE, "
+ "  INDEX `fk_booking_restaurant1_idx` (`restaurant_idRistorante` ASC) VISIBLE, "
+ "  CONSTRAINT `fk_booking_table1` "
+ "    FOREIGN KEY (`table_idtable`) "
+ "    REFERENCES `ristorante_teamproject`.`table` (`idtable`) "
+ "    ON DELETE NO ACTION "
+ "    ON UPDATE NO ACTION, "
+ "  CONSTRAINT `fk_booking_client1` "
+ "    FOREIGN KEY (`client_idcliente`) "
+ "    REFERENCES `ristorante_teamproject`.`client` (`idcliente`) "
+ "    ON DELETE NO ACTION "
+ "    ON UPDATE NO ACTION, "
+ "  CONSTRAINT `fk_booking_restaurant1` "
+ "    FOREIGN KEY (`restaurant_idRistorante`) "
+ "    REFERENCES `ristorante_teamproject`.`restaurant` (`idRistorante`) "
+ "    ON DELETE NO ACTION "
+ "    ON UPDATE NO ACTION) "
+ "ENGINE = InnoDB;";


String varname111 = ""
+ "SET SQL_MODE=@OLD_SQL_MODE;";


String varname112 = ""
+ "SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;";


String varname113 = ""
+ "SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;";